/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package algoritmos;

/**
 *
 * @author SERINAC VG
 */
public class GraficoConjunto extends javax.swing.JFrame {
    
    ClaseConjunto Muestra=new ClaseConjunto();
    int Contador=1;

    public GraficoConjunto() {
        initComponents();
        this.setLocationRelativeTo(null);
        btntranparente();
    }
    
    public void btntranparente(){
        btnsalir.setOpaque(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCr = new javax.swing.JTextField();
        txtCb = new javax.swing.JTextField();
        btnNDatosA = new javax.swing.JButton();
        btnDatosA = new javax.swing.JButton();
        btnDatosB = new javax.swing.JButton();
        btnNDatosB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimetrica = new javax.swing.JButton();
        btnDiferencia = new javax.swing.JButton();
        btnInterseccion = new javax.swing.JButton();
        btnUnion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCa = new javax.swing.JTextField();
        lblRes = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCr.setBackground(new java.awt.Color(204, 204, 255));
        txtCr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 421, 20));

        txtCb.setBackground(new java.awt.Color(204, 204, 255));
        txtCb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 363, 20));

        btnNDatosA.setBackground(new java.awt.Color(51, 153, 255));
        btnNDatosA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNDatosA.setForeground(new java.awt.Color(255, 255, 255));
        btnNDatosA.setText("N° Datos A");
        btnNDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNDatosAActionPerformed(evt);
            }
        });
        getContentPane().add(btnNDatosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        btnDatosA.setBackground(new java.awt.Color(51, 153, 255));
        btnDatosA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDatosA.setForeground(new java.awt.Color(255, 255, 255));
        btnDatosA.setText("Dato:");
        btnDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 100, -1));

        btnDatosB.setBackground(new java.awt.Color(51, 153, 255));
        btnDatosB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDatosB.setForeground(new java.awt.Color(255, 255, 255));
        btnDatosB.setText("Dato:");
        btnDatosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosBActionPerformed(evt);
            }
        });
        getContentPane().add(btnDatosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 100, -1));

        btnNDatosB.setBackground(new java.awt.Color(51, 153, 255));
        btnNDatosB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNDatosB.setForeground(new java.awt.Color(255, 255, 255));
        btnNDatosB.setText("N° Datos B");
        btnNDatosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNDatosBActionPerformed(evt);
            }
        });
        getContentPane().add(btnNDatosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel3.setText("Operaciones de Conjuntos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 360, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Alamacenamiento de datos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        btnSimetrica.setBackground(new java.awt.Color(51, 153, 255));
        btnSimetrica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimetrica.setForeground(new java.awt.Color(255, 255, 255));
        btnSimetrica.setText("Dif. Simétrica");
        btnSimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimetricaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimetrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, -1));

        btnDiferencia.setBackground(new java.awt.Color(51, 153, 255));
        btnDiferencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDiferencia.setForeground(new java.awt.Color(255, 255, 255));
        btnDiferencia.setText("Diferencia");
        btnDiferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, -1));

        btnInterseccion.setBackground(new java.awt.Color(51, 153, 255));
        btnInterseccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInterseccion.setForeground(new java.awt.Color(255, 255, 255));
        btnInterseccion.setText("Intersección");
        btnInterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterseccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnInterseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 110, -1));

        btnUnion.setBackground(new java.awt.Color(51, 153, 255));
        btnUnion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUnion.setForeground(new java.awt.Color(255, 255, 255));
        btnUnion.setText("Unión");
        btnUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Operaciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtCa.setBackground(new java.awt.Color(204, 204, 255));
        txtCa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 363, 20));

        lblRes.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblRes.setForeground(new java.awt.Color(51, 153, 255));
        lblRes.setText("RESULTADO");
        getContentPane().add(lblRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 180, -1));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 60, 40));

        btnClear.setBackground(new java.awt.Color(0, 0, 255));
        btnClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 450, 100, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_pequeño.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Conjunto B");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("Guardar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Guardar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Conjunto A");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wer.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNDatosAActionPerformed
        // TODO add your handling code here:
        Muestra.ConjuntoCa(Integer.parseInt(txtCa.getText()));
        btnDatosA.setText("Dato: 1/"+Muestra.LongA());
        txtCa.setText(null);
        txtCa.requestFocus();
        btnNDatosA.setEnabled(false);
    }//GEN-LAST:event_btnNDatosAActionPerformed

    private void btnNDatosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNDatosBActionPerformed
        // TODO add your handling code here:
        Muestra.ConjuntoCb(Integer.parseInt(txtCb.getText()));
        btnDatosB.setText("Dato: 1 /"+Muestra.LongB());
        txtCb.setText(null);
        txtCb.requestFocus();
        btnNDatosB.setEnabled(false);
    }//GEN-LAST:event_btnNDatosBActionPerformed

    private void btnDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAActionPerformed
        // TODO add your handling code here:
        Muestra.Ca(txtCa.getText(),Contador-1);
        txtCa.setText(null);
        txtCa.requestFocus();
        Contador++;

        if (Contador>Muestra.LongA()){
            for(int i=1;i<=Muestra.LongA();i++){
                txtCa.setText(txtCa.getText()+Muestra.Ca(i-1)+";");
            }
            txtCa.setText("{"+txtCa.getText()+"}");
            Contador=1;
            btnDatosA.setEnabled(false);
        }
        else{
            btnDatosA.setText("Dato: "+Contador+" / "+Muestra.LongA());
            }
                       
    }//GEN-LAST:event_btnDatosAActionPerformed

    private void btnDatosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosBActionPerformed
        // TODO add your handling code here:
        Muestra.Cb(txtCb.getText(),Contador-1);
        txtCb.setText(null);
        txtCb.requestFocus();
        Contador++;

        if (Contador>Muestra.LongB()){
            for(int i=1;i<=Muestra.LongB();i++){
                txtCb.setText(txtCb.getText()+Muestra.Cb(i-1)+";");
            }
            txtCb.setText("{"+txtCb.getText()+"}");
            Contador=1;
            btnDatosB.setEnabled(false);
        }
        else{
            btnDatosB.setText("Dato: "+Contador+" / "+Muestra.LongB());

        }                           
    }//GEN-LAST:event_btnDatosBActionPerformed

    private void btnUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionActionPerformed
        // TODO add your handling code here:
        txtCr.setText("{" +Muestra.Union()+"}"); 
        lblRes.setText("R = A"+ " U " +"B");
    }//GEN-LAST:event_btnUnionActionPerformed

    private void btnInterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterseccionActionPerformed
        // TODO add your handling code here:
        txtCr.setText("{" +Muestra.Interseccion()+"}"); 
        lblRes.setText("R = A"+ " ∩ "+ "B");
    }//GEN-LAST:event_btnInterseccionActionPerformed

    private void btnDiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiferenciaActionPerformed
        // TODO add your handling code here:
        txtCr.setText("{" +Muestra.Diferencia()+"}"); 
        lblRes.setText("R = A − B");
    }//GEN-LAST:event_btnDiferenciaActionPerformed

    private void btnSimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimetricaActionPerformed
        // TODO add your handling code here:´´
        txtCr.setText("{" +Muestra.DiferenciaSimetrica()+"}"); 
        lblRes.setText("R = A ∆ B");
    }//GEN-LAST:event_btnSimetricaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        btnNDatosA.setEnabled(true);
        btnNDatosB.setEnabled(true);
        btnDatosA.setEnabled(true);
        btnDatosB.setEnabled(true);
        txtCa.setText("0");
        txtCb.setText("0");
        txtCr.setText("0");
        lblRes.setText("Operacion:");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDatosA;
    private javax.swing.JButton btnDatosB;
    private javax.swing.JButton btnDiferencia;
    private javax.swing.JButton btnInterseccion;
    private javax.swing.JButton btnNDatosA;
    private javax.swing.JButton btnNDatosB;
    private javax.swing.JButton btnSimetrica;
    private javax.swing.JButton btnUnion;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblRes;
    private javax.swing.JTextField txtCa;
    private javax.swing.JTextField txtCb;
    private javax.swing.JTextField txtCr;
    // End of variables declaration//GEN-END:variables
}
